print("Target   http://127.0.0.1:8080/vul/rce/rce_eval.php")
print("method  version_match")
import time
print("[INFO] 开始扫描: http://127.0.0.1:8080/vul/rce/rce_eval.php")
print("正在扫描...", end="\r")
time.sleep(2)
print("[INFO] Unable to identify target, Run all pocs")
print("正在扫描...", end="\r")
time.sleep(5)
print("[?] 目标可能存在 xss/reflected 漏洞 [你需要进一步人工判断]")
time.sleep(1)
print("[+] 目标存在 cmd-injection 漏洞")
time.sleep(4)
print("[INFO] 扫描完毕")